name: online_store
description: Online clothes store.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.4
  page_transition: ^2.0.5
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  firebase_auth: ^3.3.14
  firebase_core: ^1.14.1
  firebase: ^9.0.2
  bloc: ^8.0.3
  email_validator: ^2.0.1
  google_sign_in: ^5.3.0
  username_validator: ^0.1.1
  intl_phone_number_input: ^0.7.0+2
  progress_indicators: ^1.0.0
  stylish_bottom_bar: ^0.1.2
  animation_search_bar: ^0.0.8
  flutter_facebook_auth: ^4.3.0
  concentric_transition: ^1.0.1+1
  lottie: ^1.3.0
  shared_preferences: ^2.0.15
  cloud_firestore: ^3.1.14
  flutter_screenutil: ^5.5.3+2
  flutter_add_to_cart_button: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
    - assets/fonts/



  fonts:
     - family: Montserrat
       fonts:
          - asset: assets/fonts/Montserrat-Regular.ttf
          - asset: assets/fonts/Montserrat-Thin.ttf
          - asset: assets/fonts/Montserrat-Medium.ttf

